services:
  - type: web
    name: backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: "/docs"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
  - type: static_site
    name: frontend
    rootDir: frontend
    staticPublishPath: .
    # If your frontend has a build step (e.g., React, Vue, Angular), uncomment and adjust buildCommand
    # buildCommand: npm run build
